ca_bundle = ""
hide_cpr_numbers = false
dummy_mode = true
triggers = []

[saml_sso]
name_id_format = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
signature_algorithm = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
api_token_restrict = false
force_https = true
lowercase_urlencoding = true
enable = false
idp_insecure = false
cert_file = "/certificates/saml_cert.pem"
username_attr = ""
want_name_id = true
username_from_nameid = true
requests_signed = true
api_token_restrict_attr = ""
digest_algorithm = "http://www.w3.org/2001/04/xmlenc#sha256"
duplicate_attributes = true
key_file = "/certificates/saml_key.pem"
requested_authn_context = false
idp_metadata_url = "https://idp.ballerup.dk/runtime/saml2/metadata.idp"
want_attribute_statement = false
api_token_restrict_value = ""
idp_metadata_file = ""
requested_authn_context_comparison = "exact"

[query_export]
directory = "/queries"

[configuration]
triggers = []

[configuration.database]
password = "mora"
user = "mora"
name = "mora"
host = "mox-db"
port = 5432

[configuration.amqp]
os2mo_exchange = "os2mo_queue"
enable = false
host = "localhost"
port = 5672

[external_integration]
org_unit = ""

[organisation]
user_key = ""
name = ""
uuid = ""

[service_platformen]
municipality_uuid = "00000000-0000-0000-0000-000000000000"
uuid = "00000000-0000-0000-0000-000000000000"
agreement_uuid = "00000000-0000-0000-0000-000000000000"
certificate_path = "/certificates/foces.pem"
system_uuid = "00000000-0000-0000-0000-000000000000"

[lora]
tree_search_limit = 100
default_page_size = 2000
max_request_length = 4096
url = "http://mox:8080/"

[autocomplete]
address_count = 10
access_address_count = 5

[session]
permanent = true
cookie_name = "session"
permanent_lifetime = 3600
service_session_lifetime = 2678400

[session.database]
password = "sessions"
user = "sessions"
name = "sessions"
sqlalchemy_table = "sessions"
host = "mox-db"
port = 5432
sqlalchemy_uri = ""
