base_url = ""

[restrictions]
module = "oio_rest.auth.wso_restrictions"
enable = false
function = "get_auth_restrictions"

[audit_log]
exchange = "mox.log"
ignored_services = ["Log"]
host = ""
queue = "mox.log_queue"

[saml_sso]
idp_insecure = false
requests_signed = false
cert_file = ""
key_file = ""
permanent_session_lifetime = 3600
session_permanent = true
enable = false
sqlalchemy_uri = "postgresql://sessions:sessions@127.0.0.1/sessions"
idp_metadata_url = "https://adfs.magenta.dk/federation/metadata.xml"

[file_upload]
folder = "/var/mox"

[testing_api]
enable = false

[db_extensions]
path = "oio_rest/oio_rest/db_extensions/mo-01.json"

[database]
password = "1.jZ/fDqDv1U74=3v0S}"
user = "mox"
db_name = "mox"
host = "mox-db"
port = 5432

[saml_wstrust]
idp_entity_id = "localhost"
idp_url = "https://localhost:9443/services/wso2carbon-sts.wso2carbon-stsHttpsEndpoint"
user_id_attibute = "http://wso2.org/claims/url"
idp_type = "wso2"
entity_id = "https://saml.local"
enable = false
idp_certificate = "test_auth_data/idp-certificate.pem"
